"""CLASS-N structural lint — fail-closed gate for hand-edited generated files.

Generated landing pages live under `landing/brands/{id}/index.html`.
They carry `<meta name="generator" content="KiX landing_gen ...">` so
future devs see they are auto-generated.

This lint asserts:

1. Every `landing/brands/*/index.html` IS regenerable byte-identical
   from `scripts/generate_landing_sites.py` — i.e. nobody hand-edited it
   since the last regen.

2. New landing pages outside that directory (e.g. `landing/foo.html`)
   are flagged if they LOOK like landing pages (have nav + hero + footer)
   but are not in the generated-brands path.

Exit code:
  0 = clean
  1 = drift detected (hand-edit on a generated file OR off-template landing)
  2 = setup error (script can't import landing_gen, etc.)

Wire into CI as: `python -m scripts.lint_no_handcrafted_landings`.

Run locally with `--fix` to regenerate any drifted files (interactive).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _generate_for_brand(brand_id: str) -> str | None:
    """Regenerate HTML for a brand_id using the canonical script's BRANDS dict."""
    try:
        from scripts.generate_landing_sites import BRANDS
        from app.services.landing_gen import generate_landing
    except Exception as e:
        print(f"setup-error: {e}", file=sys.stderr)
        return None

    if brand_id not in BRANDS:
        return None
    return generate_landing(BRANDS[brand_id])


def check_generated_files() -> list[str]:
    """Return list of problems found in landing/brands/*/index.html."""
    problems: list[str] = []
    brand_root = ROOT / "landing" / "brands"
    if not brand_root.exists():
        return problems

    for brand_dir in sorted(brand_root.iterdir()):
        if not brand_dir.is_dir():
            continue
        f = brand_dir / "index.html"
        if not f.exists():
            problems.append(f"missing: {f.relative_to(ROOT)}")
            continue

        on_disk = f.read_text()
        if "name=\"generator\"" not in on_disk and "name='generator'" not in on_disk:
            problems.append(
                f"no-generator-marker: {f.relative_to(ROOT)} "
                "(was it hand-authored? Should be generated.)"
            )
            continue

        expected = _generate_for_brand(brand_dir.name)
        if expected is None:
            problems.append(
                f"unknown-brand: {brand_dir.name} not in scripts/generate_landing_sites.py BRANDS"
            )
            continue

        if expected != on_disk:
            problems.append(
                f"drift: {f.relative_to(ROOT)} differs from generator output "
                f"(hand-edit? re-run `python -m scripts.generate_landing_sites`)"
            )

    return problems


def check_off_template_landings() -> list[str]:
    """Find HTML files in landing/ that LOOK like landing pages but are not
    in the generated-brands directory.

    A page "looks like a landing page" if it has:
      - <nav> or .nav class
      - "Pay only for verified" / "Free SaaS" hero copy
      - <footer>

    Allowed legacy pages (explicit allowlist) are skipped.
    """
    problems: list[str] = []
    landing_root = ROOT / "landing"
    if not landing_root.exists():
        return problems

    allowlist = {
        # Legacy hand-authored pages — track for deprecation, don't fail
        "index.html", "pricing.html", "for-chains.html", "how-we-build.html",
        "sg-case-studies.html", "play.html", "portal.html", "trinity-artifacts.html",
        "calculator.html", "enterprise.html", "calc.html", "audit.html",
        "demo.html", "trinity-protocol.html", "thanks.html", "help.html",
        "compliance.html", "terms.html", "privacy.html", "cookies.html",
        "404.html", "ahmad.html", "investors.html",
    }

    for f in sorted(landing_root.rglob("*.html")):
        rel = f.relative_to(ROOT)
        rel_str = str(rel)
        # skip generated brand dirs (checked separately)
        if "/brands/" in rel_str:
            continue
        # skip games (generated by ELTM pipeline)
        if "/games/" in rel_str:
            continue
        if f.name in allowlist:
            continue
        try:
            text = f.read_text()
        except Exception:
            continue
        looks_like_landing = (
            ("<nav" in text or 'class="nav' in text)
            and "<footer" in text
            and len(text) > 4000
        )
        if looks_like_landing:
            problems.append(
                f"off-template-landing: {rel} looks like a landing page but is "
                "not under landing/brands/ — should it be generated by landing_gen?"
            )
    return problems


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--fix", action="store_true",
                   help="(interactive) regenerate drifted files")
    args = p.parse_args()

    print(f"Linting {ROOT}/landing/brands/ ...")

    gen_problems = check_generated_files()
    off_problems = check_off_template_landings()
    problems = gen_problems + off_problems

    if not problems:
        print("✓ landing/brands/ clean — no hand-edits, no off-template pages.")
        return 0

    print(f"\n✗ {len(problems)} problem(s):")
    for prob in problems:
        print(f"  - {prob}")

    if args.fix and gen_problems:
        print("\nRegenerating drifted brand files ...")
        import subprocess
        rc = subprocess.run(
            [sys.executable, "-m", "scripts.generate_landing_sites"],
            cwd=ROOT,
        ).returncode
        if rc == 0:
            print("Done. Re-run lint to verify.")
        return rc

    print(
        "\nFix: run `python -m scripts.generate_landing_sites` (re-emit drifted files)\n"
        "  or `python -m scripts.lint_no_handcrafted_landings --fix`"
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
